// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECL.Data.ECLContext;

public partial class TDatafile
{
    public int DatafileId { get; set; }

    public string DatafileName { get; set; }

    public int DatafileType { get; set; }

    public int DatasetId { get; set; }

    public DateOnly CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateOnly? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public int IsActive { get; set; }
}