// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECL.Data.ECLContext;

public partial class TDatafileColumn
{
    public int DatafileColumnId { get; set; }

    public string DatafileColumnName { get; set; }

    public int DatafileColumnType { get; set; }

    public int DatafileId { get; set; }

    public DateOnly CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateOnly? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public int IsActive { get; set; }
}