// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECL.Data.ECLContext;

public partial class TDatasetRelations
{
    public int DatasetRelationId { get; set; }

    public int BasedataColumnId { get; set; }

    public int CashflowDataColumnId { get; set; }

    public int JoinTypeId { get; set; }

    public string MergedFileName { get; set; }

    public DateOnly CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public int IsActive { get; set; }
}