// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECL.Data.ECLContext;

public partial class TDatafileRelations
{
    public int DatafileRelationId { get; set; }

    public int SourceColumnId { get; set; }

    public int DestinationColumnId { get; set; }

    public int JoinTypeId { get; set; }

    public DateOnly CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public int IsActive { get; set; }
}