// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECL.Data.ECLContext;

public partial class TDataset
{
    public int DatasetID { get; set; }

    public string DatasetName { get; set; }

    public DateOnly CutOff { get; set; }

    public int IsRelated { get; set; }

    public int Source { get; set; }

    public DateOnly CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateOnly? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public int IsActive { get; set; }
}