// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECL.Data.ECLContext;

public partial class TJoinTypes
{
    public int JoinId { get; set; }

    public string JoinType { get; set; }

    public int IsActive { get; set; }
}