// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECL.Data.ECLContext;

public partial class TMenuMaster
{
    public int MenuId { get; set; }

    public int ModuleId { get; set; }

    public string MenuName { get; set; }

    public string MenuTag { get; set; }

    public int? ParentId { get; set; }

    public string Logo { get; set; }

    public string Route { get; set; }

    public double SequenceNo { get; set; }

    public int IsVisible { get; set; }

    public int IsActive { get; set; }
}