// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ECL.Data.ECLContext;

public partial class TUserMaster
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public int RoleId { get; set; }

    public int IsLoggedIn { get; set; }

    public int IsDeactivatedByAdmin { get; set; }

    public int IsActive { get; set; }

    public DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }
}